@server = https://fictional-couscous-vgqvx74v6cv76-8080.app.github.dev
###
GET {{server}}/api/productos/2
###
POST {{server}}/api/productos
Content-Type: application/json

{"nombre": "Creatina MyProtein", "precio": "70", "descripcion": "."}
###
GET {{server}}/api/ventas
###
POST {{server}}/api/ventas
Content-Type: application/json

{"nombre": "1 Venta"}
###
GET {{server}}/api/detalleventa
###
GET {{server}}/api/detalleventa/1
###
GET {{server}}/api/detalleventa/1/infoventa
###
GET {{server}}/api/infoventa
